### ISSUE TITLE
out of resources?

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#27]
my tests for today via fresh data have been waiting one and several hours, respectively. Is there a logjam?

**Comment by godfoder** [comment]
I just fixed it, one of our grad students left a very large notebook open.

**Comment by jhammock** [comment]
you're sure? My test queries still appear to be waiting...

**Comment by jhpoelen** [comment]
This might actually be a job summit issue - please hold on...

**Comment by jhpoelen** [comment]
@jhammock turned out to be that after my recent api changes, the api was creating requests, but not sending them. Should be fixed now, please confirm.

**Comment by jhammock** [comment]
Interesting. One of my queries completed, but this one is still stuck. I'll admit the taxon name is a typo, but I assume that has no effect.

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Lepidopa&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

**Comment by jhpoelen** [comment]
On checking mesos for running jobs, I noticed that a checklist job was running. After killing the job and requesting your "Lepidopa" query, the job started as expected. This supports the idea that it is a capacity issue, or "logjam". 

@godfoder Right now, only a single job submitted through the spark job dispatcher can be running at a time to avoid jobs flooding the cluster. You can increase (or remove) this limit by configuring the spark dispatcher running in marathon.

**Comment by jhammock** [comment]
Just one checklist query? Well, I did request a checklist a few minutes ago
(I can wait and request it again later) so I'm still not sure why the
"Lepidopa" query wasn't running yesterday or this morning...
